Str=input("Enter the String:")
print(Str[::-1])
print(Str.lower())
print(Str.upper())
print(Str.swapcase())
print(Str.startswith('P'))
print(Str.count('P'))
Str=Str.lower()
print(Str.replace('p','j'))
  